### ISSUE TITLE
Solve the potential log file overflow issue

### ISSUE THREAD

**Issue by pik4ez-canonical** [canonical/openfga-operator#97]
### Enhancement Proposal

[Log file](https://github.com/canonical/openfga-operator/blob/6d6e0a24a78d81e53b0556e61bfa34a59b492598/src/charm.py#L275) that is not rotating have a chance to overflow.

It looks like a new [Pebble Log Forwarding](https://discourse.charmhub.io/t/loki-k8s-docs-logging-via-pebble-log-forwarding/15263) feature might solve the issue. It might be possible to remove the log file altogether and use log forwarding from the stdout of the OpenFGA workload container.

**Comment by pik4ez-canonical** [comment]
Observations:
* The issue was previously addressed by logrotate. Nikos' [commit](https://github.com/canonical/openfga-operator/commit/b11c9b874ede45f3f00d02afe46db31c25fc129a) removed logrotate feature.
* Loki-k8s library needs to be updated to implement log forwarding. The bot created a [relevant PR](https://github.com/canonical/openfga-operator/pull/40/files#diff-ad7051b5ca68befcdb77d638fcfa686fa902ae8089c8e72cea3c222df01a4597) that has loki-k8s lib updated among other libs. But there exists the next version of loki-k8s library: [v1](https://charmhub.io/loki-k8s/libraries/loki_push_api). It might make sense to upgrade to v1.

**Comment by nsklikas** [comment]
>     * The issue was previously addressed by logrotate. Nikos' [commit](https://github.com/canonical/openfga-operator/commit/b11c9b874ede45f3f00d02afe46db31c25fc129a) removed logrotate feature.

Just a clarification on this: previously `logratate` was installed in the container and the charm configured it. BUT it didn't work.

Usually on a machine/VM environment `logratate` is run/managed by some service manager (e.g. `systemd`), but on a container environment, AFAIK usually a single process is run by the system (and there is no service manager). For this reason, the `logrotate` binary was there, but it was never run. 

Since we are using pebble, we have a mini service manager on each of our containers which means we could be running multiple services. But I think that this is a bad pattern (running logrotate on each container) for a container environment and it does not follow k8s best practices for managing logs. 

We knew that pebble log forwarding was in the works, for this reason we decided to go with the current approach (simply let the container die) and remove `logrotate` from the container.

**Comment by pik4ez-canonical** [comment]
@canonical/observability may I ask you to shed some light on the fate of [LogForwarder bug](https://github.com/canonical/loki-k8s-operator/issues/403) with handling alert rules? It is now required to [work around](https://github.com/canonical/openfga-operator/pull/98#issuecomment-2337685669) the issue, which creates potential maintainability issues.
